learning_settings:
  image_resolution: 256
  batch_size: 30
  num_epochs: 20
  learning_rate: 0.0001
  cnn_training_epochs: 50
  checkpoint_path_vit: "saved/vit_checkpoint.pt"
  checkpoint_path_cnn: "saved/cnn_checkpoint.pt"
  data_dir: "data_processed"

vit_model:
  patch_size: 16
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_dim: 3072
  dropout: 0.1